sudo: required

language: python

services:
    - docker

python:
    - "3.5"

cache:
  directories:
    - plugins/gui/frontend/gosa/build

before_install:
    - sudo killall -9 postgres
    - docker pull cpollmeier/gosa3:devel
    - docker run -d -p 389:389 -p 1883:1883 -p 5432:5432 cpollmeier/gosa3:devel
    - pip install setproctitle pylint tornado coveralls 'pytest>=2.9'
    - sudo [ $(ip addr show | grep "inet6 ::1" | wc -l) -lt "1" ] && sudo sed -i '/^::1/d' /etc/hosts
    - sudo sed -i '/127.0.1.1/d' /etc/hosts  # Workaround tornadoweb/tornado#1573
    - export TZ=Europe/Berlin
    - sudo mkdir /tmp/workflows
    - sudo mkdir /etc/gosa
    - sudo cp ./test_conf/config /etc/gosa/
    - sudo ls -la /etc/gosa/

script:
    - cd plugins/gui/frontend/gosa/
    - python2 generate.py -sI build
    - cd ../../../../
    - ./setup.py develop
    - ./setup.py test --addopts="--runslow"

after_success:
    - coveralls